"""create alembic properties table

Revision ID: 7042f36a83c0
Revises: 
Create Date: 2026-08-07 14:46:31.186328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7042f36a83c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_properties',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('City', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alembic_properties_id'), 'alembic_properties', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('properties',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bedrooms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bathrooms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('area_sqft', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('property_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'AVAILABLE'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("property_type::text = ANY (ARRAY['Villa'::character varying, 'Apartment'::character varying, 'House'::character varying, 'Studio'::character varying]::text[])", name=op.f('properties_property_type_check')),
    sa.CheckConstraint("status::text = ANY (ARRAY['AVAILABLE'::character varying, 'SOLD'::character varying, 'BOOKED'::character varying, 'REMOVED'::character varying]::text[])", name=op.f('properties_status_check')),
    sa.CheckConstraint('area_sqft IS NULL OR area_sqft > 0', name=op.f('properties_area_sqft_check')),
    sa.CheckConstraint('bathrooms IS NULL OR bathrooms >= 0', name=op.f('properties_bathrooms_check')),
    sa.CheckConstraint('bedrooms IS NULL OR bedrooms >= 0', name=op.f('properties_bedrooms_check')),
    sa.CheckConstraint('price > 0::numeric', name=op.f('properties_price_check')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('properties_owner_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('properties_pkey'))
    )
    op.create_table('saved_properties',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('saved_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_saved_property'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'property_id', name=op.f('saved_properties_pkey'))
    )
    op.drop_index(op.f('ix_alembic_properties_id'), table_name='alembic_properties')
    op.drop_table('alembic_properties')
    # ### end Alembic commands ###
